arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_shoulder_pan_joint
    - arm_shoulder_lift_joint
    - arm_elbow_flex_joint
    - arm_wrist_flex_joint
  gains:
    arm_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_elbow_flex_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_wrist_flex_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_joint
  gains:
    gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1