<?xml version="1.0"?>
<!-- PhantomX Pincher Arm gripper URDF-->
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:bioloid_F3_fixed parent="arm_wrist_flex_link" name="arm_wrist_F3_0" color="${color}">
      <origin xyz="0 0 ${F2_HEIGHT}" rpy="0 ${M_PI} ${-M_PI}"/>
    </xacro:bioloid_F3_fixed>
    
    <!-- gripper joint -->
    <xacro:dynamixel_AX12_fixed parent="arm_wrist_F3_0_link" name="gripper_servo" >
      <origin xyz="0 0 ${-AX12_WIDTH/2}" rpy="${M_PI/2} ${M_PI} ${M_PI/2}"/>
    </xacro:dynamixel_AX12_fixed>
    
     <xacro:gripper_finger_base parent="gripper_servo_link" name="gripper_finger_base" color="${color}">
      <origin xyz="0.015  ${AX12_WIDTH} 0" rpy="${M_PI/2} ${-M_PI} ${M_PI/2}"/>
    </xacro:gripper_finger_base>

    <joint name="gripper_joint" type="prismatic">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit effort="30" velocity="10" lower="-0.01" upper="0.01"/>
      <parent link="gripper_servo_link"/>
      <child link="gripper_active_link"/>
    </joint> 

    <!-- Finger 1 --> 
    <xacro:pincher_gripper name="gripper_active" color="Green" >
      <origin xyz="-0.02 0.04 0.0" rpy="${-M_PI/2} ${M_PI} 0"/>
    </xacro:pincher_gripper>

    <joint name="gripper2_joint" type="fixed">
      <origin xyz="0 0.04 0" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <parent link="gripper_servo_link"/>
      <child link="gripper_active2_link"/>
    </joint> 

    <!-- Finger 2 --> 
    <xacro:pincher_gripper name="gripper_active2" color="Green" >
      <origin xyz="0.025 0 0.0" rpy="${-M_PI/2} 0 0"/>
    </xacro:pincher_gripper>

    <gazebo reference="gripper_active_link">
			<mu1 value="100.0"/>
			<mu2 value="50.0"/>
			<kp value="10000000.0" />
			<kd value="1.0" />
		</gazebo>

    <gazebo reference="gripper_active2_link">
			<mu1 value="100.0"/>
			<mu2 value="50.0"/>
			<kp value="10000000.0" />
			<kd value="1.0" />
		</gazebo>

    <gazebo>
      <plugin name="gazebo_grasp_fix" filename="libgazebo_grasp_fix.so">
        <robotNamespace>/cube_stack_arm</robotNamespace>
          <arm>
            <arm_name>arm</arm_name>
            <gripper_link>gripper_active_link</gripper_link>
            <gripper_link>arm_wrist_flex_link</gripper_link>
            <palm_link>arm_wrist_flex_link</palm_link>
          </arm>   
        <forces_angle_tolerance>100</forces_angle_tolerance>
        <update_rate>4</update_rate>
        <grip_count_threshold>4</grip_count_threshold>
        <max_grip_count>8</max_grip_count>
        <release_tolerance>0.0005</release_tolerance>
        <disable_collisions_on_attach>false</disable_collisions_on_attach>
        <contact_topic>__default_topic__</contact_topic>
      </plugin>
    </gazebo>

</robot>